from aqos.persistence.database import (
    AQOS_DATABASE_VERSION,
    AqosDatabase,
    AqosDatabaseConfig,
    IN_MEMORY_DATABASE,
    open_aqos_database,
    row_to_dict,
)

from aqos.persistence.records import (
    AQOS_RECORDS_VERSION,
    EMAIL_PATTERN,
    apply_optional_updates,
    build_record_id,
    decode_bool,
    decode_json_field,
    decode_string_list,
    encode_bool,
    encode_json_field,
    encode_string_list,
    normalize_email,
    normalize_required_text,
    normalize_symbol,
    record_utc_now,
)

from aqos.persistence.schema import (
    AQOS_SCHEMA_STATEMENTS,
    AQOS_SCHEMA_TABLES,
    AQOS_SCHEMA_VERSION,
    apply_aqos_schema,
    describe_aqos_schema,
    ensure_aqos_schema,
    is_aqos_schema_current,
    list_missing_aqos_tables,
    read_aqos_schema_version,
)

from aqos.persistence.users import (
    AQOS_USER_PROFILE_VERSION,
    READ_ONLY_USER_ROLES,
    UserProfile,
    UserProfileRepository,
    UserRole,
    UserStatus,
    build_user_profile_from_row,
)

__all__ = [
    "AQOS_DATABASE_VERSION",
    "AqosDatabase",
    "AqosDatabaseConfig",
    "IN_MEMORY_DATABASE",
    "open_aqos_database",
    "row_to_dict",
    "AQOS_RECORDS_VERSION",
    "EMAIL_PATTERN",
    "apply_optional_updates",
    "build_record_id",
    "decode_bool",
    "decode_json_field",
    "decode_string_list",
    "encode_bool",
    "encode_json_field",
    "encode_string_list",
    "normalize_email",
    "normalize_required_text",
    "normalize_symbol",
    "record_utc_now",
    "AQOS_SCHEMA_STATEMENTS",
    "AQOS_SCHEMA_TABLES",
    "AQOS_SCHEMA_VERSION",
    "apply_aqos_schema",
    "describe_aqos_schema",
    "ensure_aqos_schema",
    "is_aqos_schema_current",
    "list_missing_aqos_tables",
    "read_aqos_schema_version",
    "AQOS_USER_PROFILE_VERSION",
    "READ_ONLY_USER_ROLES",
    "UserProfile",
    "UserProfileRepository",
    "UserRole",
    "UserStatus",
    "build_user_profile_from_row",
]
