"""
AQOS API package.

The API package contains framework-independent API boundary utilities.

It exposes a stable public API for:

- response envelopes
- health operations
- market operations
- strategy operations
- risk operations
- execution operations
- evaluation operations
- research operations
- memory operations
- orchestrator operations
"""

from aqos.api.evaluation import (
    BacktestNameRequest,
    CompareBacktestsRequest,
    EvaluationBacktestRequest,
    api_backtest_summary,
    api_compare_backtests,
    api_evaluation_report,
    api_performance_grade,
    api_run_backtest,
    evaluation_agent_operation,
    normalize_backtest_request,
)
from aqos.api.execution import (
    ClosePositionRequest,
    ExecutionOrderRequest,
    ExecutionTradeRequest,
    FillOrderRequest,
    OrderIdRequest,
    api_cancel_order,
    api_close_position,
    api_execute_trade,
    api_execution_summary,
    api_fill_order,
    api_order_status,
    api_place_order,
    build_execution_trade_request,
    execution_agent_operation,
    normalize_execution_trade,
)
from aqos.api.health import (
    API_SERVICE_NAME,
    API_VERSION,
    HealthCheck,
    HealthStatus,
    agent_health,
    agents_health,
    api_health,
    dependency_health,
    health_check,
    resolve_overall_health,
    system_health,
)
from aqos.api.market import (
    MarketRequest,
    api_calendar_context,
    api_market_snapshot,
    api_market_state,
    api_news_context,
    api_regime_summary,
    api_trend_summary,
    build_market_request,
    market_agent_operation,
)
from aqos.api.memory import (
    MemoryIdRequest,
    PatternMemoryRequest,
    RecallMemoryRequest,
    RememberMemoryRequest,
    TradeMemoryRequest,
    api_forget,
    api_get_memory,
    api_memory_summary,
    api_pattern_memory,
    api_recall,
    api_remember,
    api_trade_memory,
    memory_agent_operation,
    normalize_pattern_memory_request,
    normalize_recall_request,
    normalize_remember_request,
    normalize_trade_memory_request,
)
from aqos.api.orchestrator import (
    BacktestWorkflowRequest,
    MarketStrategyWorkflowRequest,
    MemoryWorkflowRequest,
    OrchestratorRouteRequest,
    ResearchWorkflowRequest,
    RiskExecutionWorkflowRequest,
    StrategyRiskWorkflowRequest,
    TradeWorkflowRequest,
    api_backtest_workflow,
    api_market_strategy_workflow,
    api_memory_workflow,
    api_orchestrator_route,
    api_research_workflow,
    api_risk_execution_workflow,
    api_strategy_risk_workflow,
    api_trade_workflow,
    orchestrator_operation,
)
from aqos.api.research import (
    CreateExperimentRequest,
    ExperimentPlanRequest,
    ResearchFindingRequest,
    ResearchHypothesisRequest,
    api_create_experiment,
    api_experiment_plan,
    api_record_finding,
    api_research_hypothesis,
    api_research_summary,
    normalize_experiment_plan_request,
    normalize_finding_request,
    normalize_hypothesis_request,
    research_agent_operation,
)
from aqos.api.responses import (
    ApiError,
    ApiResponse,
    ApiStatus,
    api_error,
    api_failure,
    api_success,
    build_api_metadata,
    exception_failure,
    not_found_failure,
    utc_timestamp,
    validation_failure,
)
from aqos.api.risk import (
    RiskTradeRequest,
    api_approve_trade,
    api_assess_trade,
    api_position_size,
    api_reject_reason,
    api_risk_handoff,
    build_risk_trade_request,
    normalize_trade_request,
    risk_agent_operation,
)
from aqos.api.strategy import (
    StrategyMarketStateRequest,
    api_entry_check,
    api_exit_check,
    api_strategy_decision,
    api_strategy_explanation,
    api_strategy_handoff,
    api_strategy_signal,
    build_strategy_market_state_request,
    normalize_market_state,
    strategy_agent_operation,
)

__all__ = [
    "API_SERVICE_NAME",
    "API_VERSION",
    "ApiError",
    "ApiResponse",
    "ApiStatus",
    "BacktestNameRequest",
    "BacktestWorkflowRequest",
    "ClosePositionRequest",
    "CompareBacktestsRequest",
    "CreateExperimentRequest",
    "EvaluationBacktestRequest",
    "ExecutionOrderRequest",
    "ExecutionTradeRequest",
    "ExperimentPlanRequest",
    "FillOrderRequest",
    "HealthCheck",
    "HealthStatus",
    "MarketRequest",
    "MarketStrategyWorkflowRequest",
    "MemoryIdRequest",
    "MemoryWorkflowRequest",
    "OrchestratorRouteRequest",
    "OrderIdRequest",
    "PatternMemoryRequest",
    "RecallMemoryRequest",
    "RememberMemoryRequest",
    "ResearchFindingRequest",
    "ResearchHypothesisRequest",
    "ResearchWorkflowRequest",
    "RiskExecutionWorkflowRequest",
    "RiskTradeRequest",
    "StrategyMarketStateRequest",
    "StrategyRiskWorkflowRequest",
    "TradeMemoryRequest",
    "TradeWorkflowRequest",
    "agent_health",
    "agents_health",
    "api_approve_trade",
    "api_assess_trade",
    "api_backtest_summary",
    "api_backtest_workflow",
    "api_calendar_context",
    "api_cancel_order",
    "api_close_position",
    "api_compare_backtests",
    "api_create_experiment",
    "api_entry_check",
    "api_error",
    "api_evaluation_report",
    "api_execute_trade",
    "api_execution_summary",
    "api_exit_check",
    "api_experiment_plan",
    "api_failure",
    "api_fill_order",
    "api_forget",
    "api_get_memory",
    "api_health",
    "api_market_snapshot",
    "api_market_state",
    "api_market_strategy_workflow",
    "api_memory_summary",
    "api_memory_workflow",
    "api_news_context",
    "api_orchestrator_route",
    "api_order_status",
    "api_pattern_memory",
    "api_performance_grade",
    "api_place_order",
    "api_position_size",
    "api_recall",
    "api_record_finding",
    "api_regime_summary",
    "api_reject_reason",
    "api_remember",
    "api_research_hypothesis",
    "api_research_summary",
    "api_research_workflow",
    "api_risk_execution_workflow",
    "api_risk_handoff",
    "api_run_backtest",
    "api_strategy_decision",
    "api_strategy_explanation",
    "api_strategy_handoff",
    "api_strategy_risk_workflow",
    "api_strategy_signal",
    "api_success",
    "api_trade_memory",
    "api_trade_workflow",
    "api_trend_summary",
    "build_api_metadata",
    "build_execution_trade_request",
    "build_market_request",
    "build_risk_trade_request",
    "build_strategy_market_state_request",
    "dependency_health",
    "evaluation_agent_operation",
    "exception_failure",
    "execution_agent_operation",
    "health_check",
    "market_agent_operation",
    "memory_agent_operation",
    "normalize_backtest_request",
    "normalize_execution_trade",
    "normalize_experiment_plan_request",
    "normalize_finding_request",
    "normalize_hypothesis_request",
    "normalize_market_state",
    "normalize_pattern_memory_request",
    "normalize_recall_request",
    "normalize_remember_request",
    "normalize_trade_memory_request",
    "normalize_trade_request",
    "not_found_failure",
    "orchestrator_operation",
    "research_agent_operation",
    "resolve_overall_health",
    "risk_agent_operation",
    "strategy_agent_operation",
    "system_health",
    "utc_timestamp",
    "validation_failure",
]